### PR TITLE
Improve directory.html

### PR DESCRIPTION
**Pull request by SatyaRF**

### CODE REVIEW

**Comment by joncojonathan** [comment]
@SatyaRF thanks for getting on this so quickly.  Would you be able to remove the duplicates (Penny Smithsons) too please?

**Comment by joncojonathan** [comment]
Addresses #1 .

**Comment by SatyaRF** [comment]
Sure I will do that. Thank you

**Comment by joncojonathan** [comment]
Many thanks for your commit :) .

**Pull request merged**
